### ISSUE TITLE
Node scanning subnets abuse

### ISSUE THREAD

**Issue by rk-p2p** [hicommonwealth/edgeware-node#133]
I running node on Hetzner cloud and get abuse for scanning subnets from rfc1918.
Is it correct behavior?
One of the old abuse:
https://pastebin.com/2qsb8Vv3

**Comment by drewstone** [comment]
Hm I am unsure about this or how it relates to the edgeware-node, maybe post in substrate related chats?

**Comment by rk-p2p** [comment]
It looks like edgeware-node start scanning the networks. When I stopped the service - scanning is finished too.
I checked it by tcpdump.
Is there any options to disable scanning or something else?

**Comment by drewstone** [comment]
@tomaka any chance you have knowledge of this?

**Comment by tomaka** [comment]
You can pass the `--no-private-ipv4` CLI flag or set [`TransportConfig::allow_private_ipv4`](https://github.com/paritytech/substrate/blob/6408967f70ff10b06b0e54017859052bd71d4258/client/network/src/config.rs#L342) to `false` in the `NetworkConfiguration` in order to ask Substrate to not connect to any RFC1918 address.

**Comment by rk-p2p** [comment]
@tomaka Thx, I'll try it!

**Comment by rk-p2p** [comment]
> You can pass the `--no-private-ipv4` CLI flag or set [`TransportConfig::allow_private_ipv4`](https://github.com/paritytech/substrate/blob/6408967f70ff10b06b0e54017859052bd71d4258/client/network/src/config.rs#L342) to `false` in the `NetworkConfiguration` in order to ask Substrate to not connect to any RFC1918 address.

It help, thx. Close the issue.
