### ISSUE TITLE
How to transfer transactions

### ISSUE THREAD

**Issue by gitcodeporter** [hicommonwealth/edgeware-node#149]
`const from = 'nx2eQN5y2B4eZRKFHsjyTG7vSP8Cq3iub9JwAQojVpM2CZK';
const to = 'nGyyxvzLHvDmzQx5viuDNTp7ZkT12DtkCEFNERHsYRw64wT';

const keyring = new Keyring({ type: 'sr25519' });
const fromPair = keyring.getPair(from);
const { nonce } = await api.query.system.account(from);
api.tx.balances.transfer(to, value).signAndSend(fromPair, { nonce }, ({ events = [], status }) => {
        console.log('status: ', status)
        console.log('Transaction status:', status.type);
        if (status.isInBlock) {
            console.log('Included at block hash', status.asInBlock.toHex());
            console.log('Events:');
            events.forEach(({ phase, event: { data, method, section } }) => {
                console.log('\t', phase.toString(), `: ${section}.${method}`, data.toString());
            });
        } else if (status.isFinalized) {
            console.log('Finalized block hash', status.asFinalized.toHex());
        }
    });
`

Error: Unable to retrieve keypair 'nx2eQN5y2B4eZRKFHsjyTG7vSP8Cq3iub9JwAQojVpM2CZK'
2020-02-28 03:59:21 852:     at assert (/user/node_modules/@polkadot/util/assert.js:34:11)
2020-02-28 03:59:21 852:     at Pairs.get (/user/node_modules/@polkadot/keyring/pairs.js:33:22)
2020-02-28 03:59:21 852:     at Keyring.getPair (/user/node_modules/@polkadot/keyring/keyring.js:225:24)
2020-02-28 03:59:21 852:     at assetsTransfer (/user/assets:37:30)
2020-02-28 03:59:21 852:     at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by ltfschoen** [comment]
It's because on line `const fromPair = keyring.getPair(from);` you're trying to retrieve a keypair from the `Keyring` instance before you've even added your keypair to the keyring. 
In the Polkadot.js API documentation, after creating an instance of the Keyring, like you've done with `const keyring = new Keyring({ type: 'sr25519' });`, you then need to add your account to the `Keyring` from either your mnemonic phrase or private key as mentioned here https://polkadot.js.org/api/start/keyring.html#adding-accounts (these differ from the public key 'nx2eQN5y2B4eZRKFHsjyTG7vSP8Cq3iub9JwAQojVpM2CZK' that's associated with your account). Alternatively you can also add it to the keyring using the @polkadot/extension-dapp library (for Desktop users that use with the Polkadot Extension) by retrieving the public keys of the accounts used in your Polkadot Extension, adding them to the injector, and then setting the signer to use the injector, so whenever you sign a transaction you'll be prompted with a popup from the Polkadot Extension asking you to sign the transaction (similar to Ethereum's MetaMask), see https://www.npmjs.com/package/@polkadot/extension-dapp#usage.
I got this to work in the FlappyTips game that I recently made, where on Mobile devices I ask them to provide their mnemonic seed, whereas on Desktop devices the have to use the Polkadot Extension (I've catered for each condition in this "if statement" https://github.com/ltfschoen/flappytips/blob/master/src/Game.js#L277).

I think this issue may be closed
