### ISSUE TITLE
Create GH action to build edgeware docker image for develop branch

### ISSUE THREAD

**Issue by yangwao** [hicommonwealth/edgeware-node#251]
Would be nice to have at least for `develop` branch up-to-date docker image for easier setup local full-node and incoming developers can test/develop against recent version with lowest effort.

Right now we have just this documented https://docs.edgewa.re/quickstart/set-up-a-full-node
Whenever it will works here, I can push to the docs.

**Comment by jiqiang90** [comment]
Hi, upload official release images on docker hub would be helpful. 

I work for OnFinality.io, as we are providing dedicated blockchain nodes on the cloud for our clients, and edgeware is one of the networks we are supporting. However, due to missing docker images, we currently have technique difficulty to run the Edgeware node. 

Please look into this as soon.

<img width="700" alt="Screen Shot 2020-11-17 at 5 27 57 PM" src="https://user-images.githubusercontent.com/10431657/99346841-741e2600-28fa-11eb-8dc9-750697d6354d.png">

**Comment by yangwao** [comment]
Hey, I'm already using unofficial from https://github.com/yangwao/substrate_playground which works well. I'll be happy to make an official one under @hicommonwealth ⛳️

**Comment by jiqiang90** [comment]
@yangwao Yes please, we still need the official one. Also, can you tag builds of that release with the release number?  Really appreciate your support
