### ISSUE TITLE
Can not get partial fee from paymentInfo

### ISSUE THREAD

**Issue by Wangmmx** [hicommonwealth/edgeware-node#281]
Hello, I want to know how to calculate the fee of the transaction. I can't find the specific fee in the transaction on the browser. The balance was different after the transfer value plus deposit fee.

I saw that the similar calculation method of project is called `paymentInfo`, but I cannot call it locally. Just like the example in the project https://github.com/hicommonwealth/frontier-tester/blob/6e583d8d8e9776058aaaa79396556e629ba3febe/web3tests/testSubstrateBalances.ts#L27, I can't run it successfully, and an error reported `Unable to query dispatch info.: Error decoding field Call :: Staking.0`

Looking forward to your reply

**Comment by jnaviask** [comment]
Can you post the code snippet you're trying?

**Comment by Wangmmx** [comment]
> Can you post the code snippet you're trying?

Yes, this is my script
```
const { ApiPromise, WsProvider } = require('@polkadot/api');

async function main () {
    
    const provider = new WsProvider('wss://mainnet1.edgewa.re');
    const api = await ApiPromise.create({ provider });

    // Retrieve the chain & node information information via rpc calls
    const [chain, nodeName, nodeVersion] = await Promise.all([
        api.rpc.system.chain(),
        api.rpc.system.name(),
        api.rpc.system.version()
    ]);

    console.log(`You are connected to chain ${chain} using ${nodeName} v${nodeVersion}`);

    const info = await api.tx.balances
        .transfer('iqbJfafvWW6Aq79WeBT4xRTcG3jU6x2K3JqzqeQ7WScfzzw', 123)
        .paymentInfo('jF5rTZxnwRmm7ztTHuKWKnJ2czBpTnS9z1oRedrxzrdvUZU');

    console.log(JSON.stringify(info))
}

main().catch(console.error).finally(() => process.exit());

```

**Comment by jnaviask** [comment]
Thanks for sharing the script! The cause of this issue is that `mainnet1.edgewa.re` is running on an older version of the node, so certain RPC features seem to not be working properly. However you can go to the polkadot apps site and paste the code into the console and it should work fine (see attached).

But if you'd rather run it locally, I hope to get a fix out for the mainnet provider this week. For the time being, if you want to keep testing, you can also run this script successfully on the testnet: `beresheet1.edgewa.re`.

![2021-01-14-112117_1860x1069_scrot](https://user-images.githubusercontent.com/1860629/104621278-eb073f00-565d-11eb-9bf5-5bd7a375bc8a.png)

**Comment by jnaviask** [comment]
I've upgraded mainnet1 and verified that your script is working. You should be good to go!

**Comment by Wangmmx** [comment]
Thank you very much! Now it is work
